### ISSUE TITLE
Support for other languajes.

### ISSUE THREAD

**Issue by brusacco** [diasks2/confidential_info_redactor_lite#1]
Hello,
Great GEM, I'm using it on a Spanish site. But I have some problems with the names that start with special chars ,,, like Óscar ... one thing I have done is change: [A-Z] with \p{Lu} ... now I get all special names.

Thanks!

**Comment by diasks2** [comment]
Thanks! I just updated the gem with that change (https://github.com/diasks2/confidential_info_redactor_lite/commit/6a31cf56d7f441a2a9f0d5384fb2f33bb90fbb1e).
